### ISSUE TITLE
missing keys for mobilenet v3-large?

### ISSUE THREAD

**Issue by ktaebum** [d-li14/mobilenetv3.pytorch#11]
Hello!

First of all, thanks for your great implementation of MobileNetV3

However, when I try to use your pretrained model (large model),

it raises error as

```
RuntimeError: Error(s) in loading state_dict for MobileNetV3:
        Missing key(s) in state_dict: "classifier.0.weight", "classifier.0.bias", "classifier.3.weight", "classifier.3.bias".
        Unexpected key(s) in state_dict: "classifier.1.weight", "classifier.1.bias", "classifier.5.weight", "classifier.5.bias".
```

Is there any difference between current implementation and pretrained checkpoint?

**Comment by aviaisr** [comment]
I'm getting the same error.

**Comment by gttiankai** [comment]
the same error

**Comment by sngyo** [comment]
I got the same error and tried to assign them manually. Looks like it works, but I don't know if this is the right approach...
```python3
state_dict = torch.load('pretrained/mobilenetv3-large-657e7b3d.pth')

state_dict["classifier.0.weight"] = state_dict["classifier.1.weight"]
del state_dict["classifier.1.weight"]

state_dict["classifier.0.bias"] = state_dict["classifier.1.bias"]
del state_dict["classifier.1.bias"]

state_dict["classifier.3.weight"] = state_dict["classifier.5.weight"]
del state_dict["classifier.5.weight"]

state_dict["classifier.3.bias"] = state_dict["classifier.5.bias"]
del state_dict["classifier.5.bias"] 

net_large.load_state_dict(                                                                                        
# torch.load('pretrained/mobilenetv3-large-657e7b3d.pth')
state_dict
)  
```

**Comment by wang-xinyu** [comment]
same error, I think maybe due to different pytorch versions.

@d-li14 could you share the version of pytorch that you were using?

**Comment by dragen1860** [comment]
the same error, please update the given pth file. Thank you.

**Comment by d-li14** [comment]
@sngyo provides the right workaround, also refer to #2. However, I will update the network structure and pre-trained models according to the revised MobileNetV3 paper soon. Stay tuned.

**Comment by d-li14** [comment]
The up-to-date release provides bug-free and stronger models now.

**Comment by mei123hao** [comment]
i find that the large pth weight key and network model key is not corresponding:
![image](https://user-images.githubusercontent.com/36464299/118663752-859da780-b823-11eb-9f1d-af0fdd1dc0e7.png)
