### ISSUE TITLE
The stride is not correct

### ISSUE THREAD

**Issue by iamhankai** [d-li14/mobilenetv3.pytorch#12]
The stride here should be 2 and the next layer should be 1, refering to https://arxiv.org/pdf/1905.02244.pdf.

https://github.com/d-li14/mobilenetv3.pytorch/blob/121d38b4e184c5dd4bd0f2df86e54cc64b0a7fe8/mobilenetv3.py#L210

**Comment by d-li14** [comment]
This implementation follows the initial version of MobileNetV3 paper, namely https://arxiv.org/abs/1905.02244v1. However, there exist typos in this version, I will update my code and retrain the models according to the latest version soon.

**Comment by d-li14** [comment]
The up-to-date release fixes.
