### ISSUE TITLE
What is Sequential() in model.classifier used for?

### ISSUE THREAD

**Issue by vinhtran1** [d-li14/mobilenetv3.pytorch#13]
Thank you for your code and pretrained model, I am a newbie in Pytorch and I have a question for the architecture. According to Pytorch document, Sequential is used to add modules.
However, in the classifier part, sequential() is empty inside. (classifier[1],  classifier[4],  classifier[5])
![image](https://user-images.githubusercontent.com/28581311/68306504-3fb73d80-00dc-11ea-967e-0f9c0b270a0c.png)
Could you please explain for me about that.
Thank you very much

**Comment by d-li14** [comment]
It's used for identity operation, the same function as `torch.nn.Identity`. BTW, I will update the code to make it more elegant soon.
