### ISSUE TITLE
About the mobilenet_v3_small_0.75 pretrained model

### ISSUE THREAD

**Issue by hungsing92** [d-li14/mobilenetv3.pytorch#14]
Many thanks for your work!!!

I want to use the mobilenet_v3_small_0.75 model, would you please upload the pretrained model?

**Comment by d-li14** [comment]
@hungsing92 Training is still in progress since the computational resource is insufficient currently. Please stay tuned. Thanks.

**Comment by d-li14** [comment]
> @hungsing92 Training is still in progress since the computational resource is insufficient currently. Please stay tuned. Thanks.

solved.

**Comment by leonard723** [comment]
Thanks for your work!

I want to use the mobilenet v3 large and small 0.75 model, but I meet some problems of size mismatch.

These are few lines of error:
RuntimeError: Error(s) in loading state_dict for MobileNetV3:
	size mismatch for features.4.conv.7.weight: copying a param with shape torch.Size([32, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([40, 96, 1, 1]).
	size mismatch for features.4.conv.8.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([40]).


Do you know how to fix it?
