### ISSUE TITLE
Question on the Madds of MobileNet-V3

### ISSUE THREAD

**Issue by blackfeather-wang** [d-li14/mobilenetv3.pytorch#15]
Thank you for your code! It is really very helpful for our project.
But I have a little question. When testing the Madds of mobilenetv3_large with Op_counter, we got 239M instead of 217M reported in the repo (Searching for MobileNetV3). Are there some differences in structures between the mobilenetv3 in this repo and the original one? Or it is due to the way to calculate Madds?

**Comment by d-li14** [comment]
How do you calculate FLOPs?

**Comment by blackfeather-wang** [comment]
Thank you for your reply. I use a convenient tool called OpCounter (https://github.com/Lyken17/pytorch-OpCounter).

**Comment by d-li14** [comment]
refer to my answer in https://github.com/d-li14/HBONet/issues/4

**Comment by blackfeather-wang** [comment]
Thanks. I'll try it with torchsummaryX:)
